++++
<a href="https://mod.io"><img src="https://mod.io/images/branding/modio-logo-bluedark.svg" alt="mod.io" width="360" align="right"/></a>
++++
# mod.io Unreal Engine Plugin

image:https://img.shields.io/badge/license-MIT-brightgreen.svg[alt="License", link="https://github.com/modio/modio-sdk/blob/master/LICENSE"]
image:https://img.shields.io/discord/389039439487434752.svg?label=Discord&logo=discord&color=7289DA&labelColor=2C2F33[alt="Discord", link="https://discord.mod.io"]
image:https://img.shields.io/badge/Unreal-4.26%2B-dea309[alt="Unreal", link="https://www.unrealengine.com"]

Welcome to the mod.io Unreal Engine Samples repository. This repository provides a simple example integration of the mod.io Unreal Engine plugin for Unreal 4.26 and Unreal 4.27 based projects. This sample project is Blueprint-only, demonstrating the core functionality of the mod.io plugin.

== Installation

Its recommended that you do a full git checkout, as the latest version of the mod.io plugin is included as a submodule. 

Once you check out the repository, you can simply launch the project in your choice of engine version (4.26 and 4.27 are supported) and Play In Editor to see the sample in action.

== Actions

There are 7 actions in total that can be performed using both keyboard and gamepad. These actions are used for navigating through the mod items or cards in-game, selecting mods from a list, and performing primary and secondary actions.

=== Navigation actions

* *Move Up*: Focus on the mod items or cards in-game by moving up. Use the up arrow or "W" on the keyboard, or the D-pad Up or Left Thumbstick Up on the gamepad.
* *Move Down*: Focus on the mod items or cards in-game by moving down. Use the down arrow or "S" on the keyboard, or the D-pad Down or Left Thumbstick Down on the gamepad.
* *Move Left*: Select the mod on the left in the list and focus on the cards in-game by moving left. Use the left arrow or "A" on the keyboard, or the D-pad Left or Left Thumbstick Left on the gamepad.
* *Move Right*: Select the mod on the right in the list and focus on the cards in-game by moving right. Use the right arrow or "D" on the keyboard, or the D-pad Right or Left Thumbstick Right on the gamepad.

=== Primary and secondary actions

* *Back*: Return to the game menu. Use the Backspace key on the keyboard, or the Face Button Right (B) on the gamepad.
* *Perform Action*: Start the game from both mod selection menu and in-game menu, and confirm the card choice in-game. Use the Enter key on the keyboard, or the Face Button Left (X) on the gamepad.
* *Perform Secondary Action*: Subscribe/Unsubscribe to the focused mod item, and use black card / show hints in-game. Use the Spacebar on the keyboard, or the Face Button Top (Y) on the gamepad.

== Known Issues

In the current release of the samples, the sample project cannot be cooked for Unreal Engine 4.27. This issue is not present when using the plugin from the Unreal Engine Marketplace, or in your own Unreal Engine project.

== Other Repositories
Our aim with https://mod.io[mod.io], is to provide an https://docs.mod.io[open modding API]. You are welcome to https://github.com/modio[view, fork and contribute to our other codebases] in use.
